### ISSUE TITLE
getting error while bower install

### ISSUE THREAD

**Issue by deepaksisodiya** [allenhwkim/angular-autocomplete#5]
This is the error

 EMALFORMED Failed to read /Users/deepak/Workspace/nite-foodie/.bower-tmp/angularjs-autocomplete-45395-cpx7kn/bower.json

**Comment by allenhwkim** [comment]
Thanks for reporting this. I will make a fix soon

**Comment by allenhwkim** [comment]
updated with 0.4.5

**Comment by deepaksisodiya** [comment]
Thanks @allenhwkim
