### ISSUE TITLE
how to set default value in multiple input field

### ISSUE THREAD

**Issue by deepaksisodiya** [allenhwkim/angular-autocomplete#6]
how to set default value in multiple input field

**Comment by allenhwkim** [comment]
Please checkout this example.  
http://rawgit.com/allenhwkim/angularjs-autocomplete/master/test/autocomplete.multi.html

This is the source code.

https://github.com/allenhwkim/angularjs-autocomplete/blob/master/test/autocomplete.multi.html

To set default values, only you need to do is to set ng-model value in your controller.

The example above is using prefillFunc, and it's setting $scope.foo.
You don't need to use prefillFunc unless you have to.

**Comment by deepaksisodiya** [comment]
Thanks @allenhwkim
